set shell := ["bash", "-c"]

config := "circleci"
project := "{{ product }}-{{ name }}"
registry := "{{ dockerfile.registry }}"

{% raw -%}
build sha:
  docker buildx build \
    --build-arg NPM_TOKEN \
    --progress "plain" \
    --tag "{{registry}}/{{project}}:{{sha}}-build" \
    --target "build" \
    .

  docker buildx build \
    --build-arg NPM_TOKEN \
    --cache-from "{{registry}}/{{project}}:{{sha}}-build" \
    --progress "plain" \
    --tag "{{registry}}/{{project}}:{{sha}}" \
    --target "service" \
    .

install:
  rm -rf node_modules
  yarn install

login:
    aws ecr get-login-password \
      --region "us-west-2" | docker login \
        --password-stdin \
        --username AWS \
            "{{registry}}"

pull sha:
    docker image pull \
        "{{registry}}/{{project}}:{{sha}}"

push sha:
  docker image push \
    "{{registry}}/{{project}}:{{sha}}"
{% endraw -%}
