---
name: project-name
template: go-lambda
parameters:
  lambdas:
    - lambda1
    - lambda2
  privateModules: "github.com/ALT-F4-LLC/quirk-service-kit"
  quirk:
    service: lambdatest
  deploy:
    - environment: dev
      if: github.ref == 'refs/heads/main'
  nix:
    vendorHash: ''
    goPackage: go_1_22
    buildGoModule: buildGo122Module
  openapi:
    enable: true
