---
name: project-name
template: go-cobra-cli
parameters:
  nix:
    cachix:
      binaryCache: altf4llc-os
    vendorHash: sha256-6B9O6ho4COpJy4HlkzQ0lk+ieezRO3xg9LyLHzoxYzc=
    goPackage: go_1_22
    buildGoModule: buildGo122Module
