build:
    go build -o {{ .Name }} ./cmd/{{ .Name }}/main.go

check:
    nix flake check

package profile='default'{{ if .PrivateModules }} netrc="/tmp/.netrc=/tmp/.netrc"{{ end }}:
    nix build \
        --json \
        --no-link \
        --print-build-logs \
        {{- if .PrivateModules }}
        --sandbox \
        --sandbox-paths "{{"{{"}} netrc {{"}}"}}" \
        {{- end }}
        '.#{{"{{"}} profile {{"}}"}}'

package-docker{{ if .PrivateModules }} netrc="/tmp/.netrc=/tmp/.netrc"{{ end }}: (package 'docker'{{ if .PrivateModules }} netrc{{ end }})
