name: terraform

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHIX_BINARY_CACHE: {{ .Nix.Cachix.BinaryCache }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{"{{"}} secrets.CACHIX_AUTH_TOKEN {{"}}"}}
          name: ${{"{{"}} env.CACHIX_BINARY_CACHE {{"}}"}}
      - uses: actions/checkout@v4
      - run: nix develop -c just check

  package:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{"{{"}} secrets.ALTF4LLC_CACHIX_AUTH_TOKEN {{"}}"}}
          name: ${{"{{"}} env.CACHIX_BINARY_CACHE {{"}}"}}
      - uses: actions/checkout@v4
      - run: nix develop -c just package
