set shell := ["bash", "-c"]

config := "circleci"
project := "{{ product }}-{{ name }}"
registry := "{{ dockerfile.registry }}"

{% raw -%}
build sha:
  docker buildx build \
    --progress "plain" \
    --tag "{{registry}}/{{project}}:{{sha}}" \
    .

install:
  rm -rf node_modules
  yarn install

login:
    aws ecr get-login-password \
      --region "us-west-2" | docker login \
        --password-stdin \
        --username AWS \
            "{{registry}}"

preview stack:
    doppler run --config "{{config}}" --project "{{project}}" -- \
        pulumi preview \
            --diff \
            --non-interactive \
            --stack "{{stack}}"

pull sha:
    docker image pull \
        "{{registry}}/{{project}}:{{sha}}"

push sha:
  docker image push \
    "{{registry}}/{{project}}:{{sha}}"

refresh stack:
    doppler run --config "{{config}}" --project "{{project}}" -- \
        pulumi refresh \
            --diff \
            --non-interactive \
            --skip-preview \
            --stack "{{stack}}" \
            --yes

update stack:
    doppler run --config "{{config}}" --project "{{project}}" -- \
        pulumi update \
          --diff \
          --non-interactive \
          --stack "{{stack}}" \
          --yes
{% endraw -%}
