#░█▀█░█░█░▀█▀░█▀█░░░░░█▀▀░█▀▀░█▀█░█▀▀░█▀▄░█▀█░▀█▀░█▀▀░█▀▄
#░█▀█░█░█░░█░░█░█░▄▄▄░█░█░█▀▀░█░█░█▀▀░█▀▄░█▀█░░█░░█▀▀░█░█
#░▀░▀░▀▀▀░░▀░░▀▀▀░░░░░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀░▀░░▀░░▀▀▀░▀▀░
# DO NOT UPDATE: This file is managed by "build-configs"

set shell := ["bash", "-c"]

build sha{% if pulumi.npm %} $NPM_TOKEN=`doppler secrets get --plain --config "circleci" --project "{{ product }}-{{ name }}" NPM_TOKEN`{% endif %}:
  docker buildx build \
    {% if pulumi.npm %}--build-arg NPM_TOKEN \{% endif %}
    --progress "plain" \
    --tag "{{ dockerfile.registry }}/{{ product }}-{{ name }}:{% raw %}{{sha}}{% endraw %}" \
    .

install:
  rm -rf node_modules
  yarn install

login:
    aws ecr get-login-password \
      --region "us-west-2" | docker login \
        --password-stdin \
        --username AWS \
            "{{ dockerfile.registry }}"

preview stack:
    doppler run --config "circleci" --project "{{ product }}-{{ name }}" -- \
        pulumi preview \
            --diff \
            --non-interactive \
            --stack "{% raw %}{{stack}}{% endraw %}"

pull sha:
    docker image pull \
        "{{ dockerfile.registry }}/{{ product }}-{{ name }}:{% raw %}{{sha}}{% endraw %}"

push sha:
  docker image push \
    "{{ dockerfile.registry }}/{{ product }}-{{ name }}:{% raw %}{{sha}}{% endraw %}"

refresh stack:
    doppler run --config "circleci" --project "{{ product }}-{{ name }}" -- \
        pulumi refresh \
            --diff \
            --non-interactive \
            --skip-preview \
            --stack "{% raw %}{{stack}}{% endraw %}" \
            --yes

update stack:
    doppler run --config "circleci" --project "{{ product }}-{{ name }}" -- \
        pulumi update \
          --diff \
          --non-interactive \
          --stack "{% raw %}{{stack}}{% endraw %}" \
          --yes

{% if pulumi.eks_cluster != "" -%}
update-kubeconfig:
    doppler run --config "circleci" --project "{{ product }}-{{ name }}" -- \
        aws eks update-kubeconfig --name "{{ pulumi.eks_cluster }}"
{%- endif %}
