name: build-and-release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: cachix/install-nix-action@v20

    - uses: actions/checkout@v3

    - name: Build binary
      run: |
        nix build --json > output.json
