name: build-and-release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: cachix/install-nix-action@v20

    - uses: cachix/cachix-action@v12
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: ${{ vars.CACHIX_CACHE_NAME }}

    - uses: actions/checkout@v3

    - name: Build binary
      run: |
        nix build --json > output.json

    - name: Cache binary
      run: |
        cat output.json \
          | jq -r '.[].outputs | to_entries[].value' \
          | cachix push '${{ vars.CACHIX_CACHE_NAME }}'

    - name: Cache inputs
      run: |
        nix flake archive --json \
            | jq -r '.path,(.inputs|to_entries[].value.path)' \
            | cachix push '${{ vars.CACHIX_CACHE_NAME }}'
