name: golangci-lint

on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  lint:
    env:
      CGO_ENABLED: 0
      GOPRIVATE: github.com/ALT-F4-LLC/quirk-service-kit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go mod download
      - uses: golangci/golangci-lint-action@v4
        with:
          skip-pkg-cache: true
          args: ./... --timeout=5m
